### ISSUE TITLE
Vẫn hiển thị mật khẩu ở payload khi đăng nhập

### ISSUE THREAD

**Issue by lehahung2k** [lehahung2k/computer-engineering-project#27]
Khi đăng nhập hệ thống, gõ tk và mk, bấm login.
Mở F12, vào network, xem payload. Tk và mk vẫn hiện

**Comment by vudinhhieu20** [comment]
Tham khảo theo một số link dưới thì phần payload chỉ hiển thị trên browser của mình thôi còn lại đã được mã hóa nên an toàn nhé
[https://www.quora.com/How-is-the-post-request-safe-when-anyone-can-find-the-password-you-entered-in-the-network-section-of-chrome-developer-tools](url)

[https://stackoverflow.com/questions/27952182/how-make-the-form-password-data-hidden-in-chrome-developer-tools-network-pannel](url)

[https://stackoverflow.com/questions/45345146/is-it-secure-to-send-username-and-password-in-a-json-object-in-the-body-of-a-pos](url)
